/* TeachMeJEE — NEET track: biology topics with notes + practice bank.
   model: sim name registered in js/sim/simsBio.js (optional). */

export const NEET_TOPICS = [
  { id: "n-cell", unit: "Cell biology", name: "Cell: the unit of life", model: "bio-cell", qcount: 14,
    summary: "Cell theory, prokaryotic vs eukaryotic organisation, and the structure-function story of every organelle.",
    points: [
      "Cell theory: Schleiden & Schwann; virchow added omnis cellula-e cellula.",
      "Fluid mosaic model (Singer & Nicolson, 1972) — phospholipid bilayer with lateral-moving proteins.",
      "Prokaryotes: 70S ribosomes, mesosome-like infoldings, no membrane-bound organelles.",
      "Mitochondria & chloroplasts carry their own circular DNA and 70S ribosomes (semi-autonomous).",
      "Rough ER studded with ribosomes handles protein synthesis; smooth ER makes lipids and steroids.",
      "Nucleolus synthesises rRNA; ribosomes assemble in cytoplasm (protein factories).",
      "Lysosomes (suicidal bags) digest via hydrolytic enzymes at acidic pH.",
      "Glyoxysomes (plants) and peroxisomes handle photorespiration and lipid oxidation.",
      "Middle lamella cements plant cells; plasmodesmata connect cytoplasms.",
      "Cell wall: primary (pectin/cellulose, growing) vs secondary (lignin, dead xylem).",
    ],
    terms: ["Fluid mosaic", "Cristae", "Glycocalyx", "Tonoplast"] },
  { id: "n-biomol", unit: "Cell biology", name: "Biomolecules", qcount: 10,
    summary: "The chemistry of life: amino acids to proteins, nucleotides to nucleic acids, plus enzymes as catalysts.",
    points: [
      "20 standard amino acids; peptide bond is an amide linkage formed by dehydration.",
      "Primary→quaternary protein structure; denaturation destroys secondary/tertiary but not primary.",
      "Nucleic acids: phosphodiester bonds join 3'→5'; DNA double helix is antiparallel.",
      "Enzymes lower activation energy; Michaelis constant Km measures substrate affinity inversely.",
      "Competitive inhibitors raise apparent Km; Vmax unchanged.",
      "Reducing sugars (glucose, fructose, maltose, lactose) reduce Benedict/Fehling; sucrose does not.",
      "Proteins: primary sequence → secondary α-helix/β-sheet → tertiary 3D → quaternary subunits.",
      "Denaturation destroys 2°/3° structure (heat, pH) without breaking peptide bonds.",
      "Nucleotides: nitrogen base + pentose + phosphate; ATP is the energy currency.",
      "Saturated fats pack straight (solid); cis-unsaturated kinks stay liquid (oils).",
    ],
    terms: ["Zwitterion", "Apoenzyme", "Holoenzyme", "Km"] },
  { id: "n-celldiv", unit: "Cell biology", name: "Cell cycle & division", qcount: 12, model: "bio-mitosis",
    summary: "Interphase business, the four phases of mitosis, and the reductional drama of meiosis.",
    points: [
      "Interphase: G1 growth, S DNA synthesis, G2 preparation — longest phase overall.",
      "Metaphase plates chromosomes at the equator; spindle fibres attach at kinetochores.",
      "Crossing over occurs in pachytene of prophase-I; synaptonemal complex forms in zygotene.",
      "Meiosis-I is reductional, meiosis-II equational.",
      "Terminalisation of chiasmata happens in diakinesis.",
      "G0: quiescent cells exit the cycle; nerve cells stay permanently in G0.",
      "Anaphase-A moves chromosomes (kinetochore microtubules shorten); anaphase-B elongates the spindle.",
      "Cytokinesis differs: cell plate (plants, Golgi vesicles) vs cleavage furrow (animals, actin).",
      "Meiosis produces 4 haploid cells; arrest points include dictyate (oocytes) and metaphase-II.",
      "Colchicine arrests at metaphase (spindle poison); cyclins + Cdks drive checkpoints.",
    ],
    terms: ["Kinetochore", "Bivalent", "Chiasmata", "Cytokinesis"] },

  { id: "n-digest", unit: "Human physiology", name: "Digestion & absorption", qcount: 9,
    summary: "From buccal cavity to large intestine — enzymes, hormones and the villus machinery of absorption.",
    points: [
      "Salivary amylase starts starch digestion; optimum pH ~6.8.",
      "Chief cells secrete pepsinogen; parietal cells HCl and intrinsic factor.",
      "Chyme enters duodenum; bile (no enzymes) emulsifies fats.",
      "Pancreatic juice: trypsinogen, chymotrypsinogen, amylase, lipase, DNase/RNase.",
      "Micelles and chylomicrons carry digested fats into lacteals.",
      "Gastric HCl (pH ~1.8) kills microbes and activates pepsinogen → pepsin.",
      "Secretin triggers bicarbonate release; CCK triggers bile + pancreatic enzymes.",
      "Succus entericus completes digestion: maltase, lactase, sucrase, dipeptidases.",
      "Villi + microvilli amplify surface ~600×; absorbed glucose/amino acids enter blood capillaries.",
      "Large intestine absorbs water and salts; gut flora synthesise vitamin K and B12.",
    ],
    terms: ["Zymogen", "Villi", "Chyle", "Brunner's glands"] },
  { id: "n-breathe", unit: "Human physiology", name: "Breathing & gas exchange", qcount: 8, model: "bio-lung",
    summary: "Mechanics of breathing, respiratory volumes and how O2/CO2 actually travel in blood.",
    points: [
      "Inspiration is active (diaphragm + external intercostals); quiet expiration passive.",
      "Oxygen mostly (97%) travels bound to haemoglobin as oxyhaemoglobin.",
      "CO2: ~7% dissolved, ~23% carbaminohaemoglobin, ~70% as bicarbonate via carbonic anhydrase.",
      "Haldane effect: oxygenation favours CO2 release in lungs.",
      "Pneumotaxic centre (pons) moderates breathing rate; chemosensors respond mainly to CO2/H+.",
      "Tidal volume ~500 mL; vital capacity ~3.5–4.5 L; residual volume never leaves.",
      "Alveoli: thin squamous walls + rich capillaries = minimal diffusion distance.",
      "Oxyhaemoglobin curve is sigmoid; right shift (Bohr: CO2, H+, heat) unloads O2.",
      "Emphysema destroys alveolar walls; asthma narrows bronchioles (wheezing).",
      "Foetal haemoglobin (HbF, α2γ2) binds O2 more avidly than adult HbA.",
    ],
    terms: ["Tidal volume", "Bohr effect", "Carbonic anhydrase", "Dead space"] },
  { id: "n-circulation", unit: "Human physiology", name: "Body fluids & circulation", qcount: 11,
    summary: "Blood composition, the cardiac cycle, ECG basics and blood-clotting cascade.",
    points: [
      "Plasma ~55%, formed elements ~45%; RBC count ~5–5.5 million/mm³.",
      "SA node = pacemaker (~70/min); cardiac muscle is myogenic.",
      "Cardiac output ≈ stroke volume × heart rate ≈ 5 L/min.",
      "QRS complex marks ventricular depolarisation; T wave repolarisation.",
      "Clotting: thrombin converts fibrinogen → fibrin; Ca²⁺ ions essential throughout.",
      "Double circulation: pulmonary (right heart → lungs) + systemic (left heart → body).",
      "SA node paces (~72/min); AV node delays; bundle of His + Purkinje spread the wave.",
      "ECG: P (atrial depolarisation), QRS (ventricular depolarisation), T (repolarisation).",
      "Blood pressure 120/80 mmHg; hypertension damages heart, brain, kidneys.",
      "Lymph returns tissue fluid; spleen filters blood and stores platelets.",
    ],
    terms: ["Diastole", "Sinoatrial node", "Universal donor", "Fibrin"] },
  { id: "n-excretory", unit: "Human physiology", name: "Excretory products & elimination", qcount: 9, model: "bio-nephron",
    summary: "Nephron fine-tuning: ultrafiltration, selective reabsorption, secretion and the hormone control of water.",
    points: [
      "Ultrafiltration in glomerulus: GFR ≈ 125 mL/min (~180 L/day).",
      "PCT reabsorbs ~70–80% of filtrate including glucose and amino acids.",
      "ADH opens collecting-duct aquaporins; aldosterone drives Na⁺ reabsorption.",
      "Countercurrent multiplier of Henle's loop builds medullary osmotic gradient.",
      "Liver forms urea via the ornithine cycle; ammonia is the most toxic nitrogenous waste.",
      "Nephron parts: glomerulus → Bowman's capsule → PCT → loop of Henle → DCT → collecting duct.",
      "GFR ~125 mL/min; glucose fully reabsorbed in PCT (no glucose in normal urine).",
      "Loop of Henle builds medullary gradient; ADH (vasopressin) inserts aquaporins in DCT/CD.",
      "Aldosterone reabsorbs Na+ (and water) in DCT; ANF opposes it.",
      "Urea cycle (ornithine cycle) runs in liver; uricotelic birds/reptiles save water.",
    ],
    terms: ["Nephron", "Aquaporin", "Uremia", "Renin"] },
  { id: "n-locomotion", unit: "Human physiology", name: "Locomotion & movement", qcount: 7, model: "bio-muscle",
    summary: "Muscle ultrastructure, sliding-filament contraction, and the skeletal joints that make motion possible.",
    points: [
      "Sarcomere = functional unit; A-band constant length, I-band and H-zone shorten on contraction.",
      "Ca²⁺ binds troponin, exposing actin sites for myosin heads.",
      "ATP powers cross-bridge cycling; rigor state when ATP absent.",
      "H-zone contains only thick filaments.",
      "Ball-and-socket joints (shoulder, hip) give the widest range of movement.",
      "Sliding filament: myosin headsratchet actin inward; H-zone and I-band shrink, A-band fixed.",
      "ATP powers cross-bridge detachment; rigor mortis is ATP exhaustion locking bridges.",
      "Red (slow, myoglobin-rich, aerobic) vs white (fast, glycolytic) muscle fibres.",
      "Ball-and-socket (shoulder), hinge (elbow/knee), pivot (neck), gliding (wrist) joints.",
      "Myasthenia gravis (autoimmune ACh receptors), tetany (low Ca2+ spasms), osteoporosis (low oestrogen).",
    ],
    terms: ["Sarcomere", "Troponin", "Synovial fluid", "Gout"] },
  { id: "n-neural", unit: "Human physiology", name: "Neural control & coordination", model: "bio-neuron", qcount: 12,
    summary: "Resting potential to action potential to synapse — the electrical language of the nervous system.",
    points: [
      "Resting membrane potential ≈ −70 mV, maintained by Na⁺/K⁺ pump (3 Na⁺ out : 2 K⁺ in).",
      "Threshold triggers all-or-none action potential; overshoot reaches about +30 mV.",
      "Saltatory conduction jumps between nodes of Ranvier in myelinated axons.",
      "Chemical synapses release neurotransmitter into the cleft; acetylcholine is excitatory at NMJ.",
      "Midbrain corpora quadrigemina handle visual/auditory reflexes; medulla controls vital centres.",
      "Resting potential −70 mV (K+ leak + Na+/K+ pump 3Na+ out, 2K+ in).",
      "Action potential: Na+ influx (depolarise) → K+ efflux (repolarise) → refractory period.",
      "Saltatory conduction jumps node to node in myelinated axons (Schwann/neurilemma).",
      "Synapse: Ca2+ entry releases acetylcholine; cholinesterase clears the cleft.",
      "Brain: cerebrum (thought), cerebellum (balance), medulla ( heart/breathing reflexes).",
    ],
    terms: ["Node of Ranvier", "Saltatory", "Neurotransmitter", "CSF"] },
  { id: "n-hormone", unit: "Human physiology", name: "Chemical coordination", qcount: 8,
    summary: "Endocrine glands, their hormones and feedback loops — slow, wide-reaching signalling.",
    points: [
      "Anterior pituitary trophic hormones: GH, TSH, ACTH, LH, FSH, prolactin.",
      "ADH and oxytocin are synthesised in hypothalamus, released from posterior pituitary.",
      "Insulin (β-cells) lowers blood glucose; glucagon (α-cells) raises it.",
      "Thyroid needs iodine; deficiency of thyroid hormones in children causes cretinism.",
      "Adrenal cortex three zones: mineralocorticoids, glucocorticoids, sex corticoids.",
      "Hypothalamus releases GnRH/TRH via portal vein; posterior pituitary releases oxytocin + ADH.",
      "GH excess: gigantism (child) / acromegaly (adult); deficiency: dwarfism.",
      "Thyroxine needs iodine; deficiency causes goitre and cretinism; Graves' disease is hyperthyroid autoimmunity.",
      "Insulin lowers glucose (diabetes = deficiency/resistance); glucagon raises it — antagonistic pair.",
      "Adrenaline (emergency) vs cortisol (stress metabolism); aldosterone conserves Na+.",
    ],
    terms: ["Second messenger", "Cretinism", "Addison's disease", "Islets"] },

  { id: "n-inherit", unit: "Genetics & evolution", name: "Principles of inheritance", qcount: 13,
    summary: "Mendel's ratios, linkage deviations, pedigree analysis and human genetic disorders.",
    points: [
      "Dihybrid F2 phenotypic ratio 9:3:3:1; test cross confirms heterozygosity.",
      "Incomplete dominance (snapdragon) gives 1:2:1 phenotypes.",
      "Linkage violates independent assortment; recombination frequency maps gene distance (cM).",
      "Haemophilia & sickle-cell anaemia: recessive; colour blindness X-linked recessive.",
      "Down (21), Klinefelter (XXY), Turner (XO) — chromosomal disorders.",
      "Mendel's laws: dominance, segregation (gamete purity), independent assortment (dihybrid 9:3:3:1).",
      "Incomplete dominance (snapdragon pink) and codominance (AB blood group) break blending.",
      "Sex-linked: haemophilia and colour blindness (X-linked recessive, males affected).",
      "Pedigree symbols: squares males, circles females; shaded = affected.",
      "Pleiotropy (one gene, many traits: sickle cell) vs polygenic (skin colour, continuous).",
    ],
    terms: ["Test cross", "Co-dominance", "Pedigree", "Trisomy"] },
  { id: "n-molecular", unit: "Genetics & evolution", name: "Molecular basis of inheritance", model: "bio-dna", qcount: 14,
    summary: "DNA as the genetic material — replication machinery, transcription, the genetic code and operons.",
    points: [
      "Griffith → Avery: transforming principle is DNA; Hershey-Chase sealed it.",
      "Helicase unwinds; DNA polymerase III synthesises 5'→3', leading continuous / lagging Okazaki.",
      "Central dogma: DNA → RNA → protein; reverse transcription in retroviruses.",
      "Genetic code: triplet, degenerate, non-overlapping, universal; AUG start.",
      "Lac operon induced by allolactose; tryptophan operon is repressible.",
      "Griffith (transformation) → Avery (DNA) → Hershey–Chase (blender: DNA enters, protein stays out).",
      "Chargaff: A=T, G≡C; antiparallel strands, 3.4 nm pitch, 10 bp per turn.",
      "Central dogma: DNA → RNA (transcription) → protein (translation); reverse transcriptase in retroviruses.",
      "Lac operon: regulator i, promoter p, operator o; lactose (allolactose) switches it on.",
      "DNA fingerprinting uses VNTR minisatellites; PCR amplifies with Taq polymerase.",
    ],
    terms: ["Okazaki", "Primosome", "cDNA", "Operon"] },
  { id: "n-evolution", unit: "Genetics & evolution", name: "Evolution", qcount: 9,
    summary: "From Miller-Urey sparks to Darwin's finches and Hardy-Weinberg equilibria.",
    points: [
      "Miller-Urey (1953): electric discharge over CH4/NH4/H2/H2O yielded amino acids.",
      "Darwinian fitness = reproductive success; natural selection acts on phenotypes.",
      "Hardy-Weinberg: p² + 2pq + q² = 1; disturbance = evolution in progress.",
      "Darwin's finches show adaptive radiation (also Australian marsupials).",
      "Homology indicates common ancestry; analogy (wings) convergent evolution.",
      "Darwin: variation + overproduction + natural selection → descent with modification.",
      "Hardy–Weinberg p²+2pq+q²=1 holds without selection, mutation, migration, drift.",
      "Homologous (same origin: forelimbs) vs analogous (same function: wings) organs.",
      "Miller–Urey sparked CH4/NH3/H2 into amino acids — chemical evolution proof-of-concept.",
      "Human story: Dryopithecus → Australopithecus → Homo habilis → erectus → sapiens (Cro-Magnon).",
    ],
    terms: ["Gene pool", "Stabilising selection", "Founder effect", "Convergence"] },

  { id: "n-humanrep", unit: "Reproduction", name: "Human reproduction", qcount: 10,
    summary: "Gametogenesis, the ovarian/menstrual cycle, fertilisation and gestational milestones.",
    points: [
      "Spermatogenesis under FSH + testosterone; Sertoli cells nurse sperm.",
      "Ovulation triggered by LH surge around day 14.",
      "Corpus luteum secretes progesterone maintaining endometrium.",
      "Fertilisation at ampullary-isthmic junction; acrosome reaction precedes it.",
      "hCG keeps corpus luteum alive early in pregnancy (pregnancy-test hormone).",
      "Spermatogenesis in seminiferous tubules (Sertoli nurse cells); ~64-day cycle.",
      "Oogenesis arrests in prophase-I before birth; one ovum per cycle after puberty.",
      "Menstrual cycle ~28 days: proliferative (oestrogen) → ovulation day ~14 (LH surge) → secretory (progesterone).",
      "Fertilisation in ampulla; cortical reaction blocks polyspermy; cleavage → morula → blastocyst.",
      "Placenta secretes hCG (pregnancy test), progesterone, oestrogen; parturition triggered by oxytocin + foetal signals.",
    ],
    terms: ["Acrosome", "Morula", "Parturition", "Lactation"] },
  { id: "n-reprohealth", unit: "Reproduction", name: "Reproductive health", qcount: 6,
    summary: "Contraception strategies, ART options and the public-health side of reproduction.",
    points: [
      "Natural, barrier (condom), IUDs (Cu-T), oral pills, surgical methods.",
      "Cu ions suppress sperm motility; hormone pills inhibit ovulation.",
      "IVF-ET, ZIFT, GIFT are assisted reproductive technologies.",
      "Amniocentesis is misused for sex determination — legally banned for that purpose.",
      "STIs: early detection, complete course of prescribed antibiotics.",
      "Contraception: barrier (condoms), IUDs (CuT), pills (progesterone–oestrogen), surgical sterilisation.",
      "MTP legal in India up to 24 weeks under conditions (MTP Act, amended 2021).",
      "STIs: gonorrhoea, syphilis (bacterial, curable) vs HIV, genital herpes/HPV (viral, managed).",
      "Infertility fixes: IVF–ET (test tube baby), ZIFT, GIFT, ICSI, artificial insemination.",
      "Amniocentesis detects genetic defects — legally banned for sex determination (PCPNDT Act).",
    ],
    terms: ["IUD", "ART", "Amniocentesis", "MTP"] },

  { id: "n-plantking", unit: "Plant diversity & morphology", name: "Plant kingdom", qcount: 9,
    summary: "Algae to angiosperms — classification anchors and life-cycle patterns across groups.",
    points: [
      "Chlorophyceae (green algae) store starch; phycobilins colour Rhodophyceae red.",
      "Bryophytes: amphibians of plant kingdom; dominant gametophyte.",
      "Pteridophytes first true vascular tissue; independent sporophyte.",
      "Gymnosperm ovules naked; pollen chambers in Cycas.",
      "Embryophyta land plants share alternation of generations.",
      "Algae: chlorophyceae (starch, green), phaeophyceae (laminarin, brown), rhodophyceae (floridean starch, red).",
      "Bryophytes need water for fertilisation (amphibians of plant kingdom); dominant gametophyte.",
      "Pteridophytes: first vascular plants with true root/stem/leaf; spores homosporous mostly.",
      "Gymnosperms naked seeds on cones; Cycas has coralloid roots with cyanobacteria.",
      "Angiosperms: covered seeds, double fertilisation, most diverse plant group.",
    ],
    terms: ["Thallus", "Prothallus", "Double fertilisation", "Heterospory"] },
  { id: "n-morphology", unit: "Plant diversity & morphology", name: "Morphology of flowering plants", qcount: 8,
    summary: "Root/stem/leaf adaptations, inflorescence types, flower formula and fruit classification.",
    points: [
      "Tap vs fibrous vs adventitious roots; pneumatophores in mangroves.",
      "Opposite/alternate/whorled phyllotaxy; tendril of pea is leaflet modification.",
      "Racemose inflorescence grows indeterminately; cymose determinately.",
      "Aestivation types: valvate, twisted, imbricate, vexillary (papilionaceous).",
      "Tomato & banana are parthenocarpic-ish berries; mango is drupe.",
      "Root mods: taproot storage (carrot), adventitious prop (banyan), pneumatophores (mangrove breathing).",
      "Stem mods: tendril (cucumber), thorn (citrus), phylloclade (Opuntia), rhizome/tuber/bulb storage.",
      "Leaf mods: tendrils (pea), spines (cactus), pitcher (Nepenthes), bladderwort traps.",
      "Inflorescence: racemose (acropetal, main axis grows) vs cymose (basipetal, terminates in flower).",
      "Aestivation: valvate, twisted, imbricate, vexillary (pea: standard/wings/keel).",
    ],
    terms: ["Phyllotaxy", "Epipetalous", "Drupe", "Perigynous"] },
  { id: "n-anatomy", unit: "Plant diversity & morphology", name: "Anatomy of flowering plants", qcount: 7,
    summary: "Monocot vs dicot internal architecture, secondary growth and wood anatomy.",
    points: [
      "Dicot root xylem radial & exarch; monocot stem scattered vascular bundles closed.",
      "Dicot stem bundles open (fascicular cambium) enabling secondary growth.",
      "Periderm = phellogen + phellem + phelloderm replaces epidermis.",
      "Spring wood light, autumn wood dense — together an annual ring.",
      "Heartwood dead but durable; sapwood conducts.",
      "Simple permanent tissues: parenchyma (storage), collenchyma (living support), sclerenchyma (dead, lignified).",
      "Complex tissues: xylem (vessels + tracheids conduct water) and phloem (sieve tubes + companion cells).",
      "Dicot root: 2–4 xylem patches, pith small; monocot root: many patches, large pith.",
      "Dicot stem: ring vascular bundles, cambium present; monocot: scattered, closed bundles.",
      "Stomata: dumb-bell guard cells in grasses, kidney-shaped in dicots; transpiration pull lifts sap.",
    ],
    terms: ["Endodermis", "Casparian strip", "Annual ring", "Heartwood"] },

  { id: "n-photo", unit: "Plant physiology", name: "Photosynthesis", model: "bio-photo", qcount: 13,
    summary: "Light reactions in thylakoids, Calvin cycle in stroma, and the C4/CAM refinements.",
    points: [
      "Light reaction (thylakoid): PSII splits water, makes ATP + NADPH; PSI reduces NADP⁺.",
      "Calvin cycle (stroma): carboxylation by RuBisCO, reduction, regeneration.",
      "C4 plants: Hatch-Slack pathway concentrates CO2; Kranz anatomy with bundle sheath.",
      "Photorespiration wasteful — RuBisCO's oxygenase activity on C3 plants.",
      "CAM plants open stomata at night (desert adaptation); acids stored till day.",
      "Chlorophyll a is the reaction-centre pigment; accessory b, xanthophylls, carotenoids widen capture.",
      "PS-II (P680, water splitting) feeds electrons to PS-I (P700, NADP+ reduction) — Z-scheme.",
      "Photolysis: 2H2O → 4H+ + 4e− + O2 at the oxygen-evolving complex (Mn cluster).",
      "C4 (maize): Kranz anatomy, PEPcase first fixation, no photorespiration — tropical advantage.",
      "CAM plants (cacti) fix CO2 at night (malic acid) and run Calvin by day with closed stomata.",
    ],
    terms: ["RuBisCO", "Bundle sheath", "Photolysis", "Z scheme"] },
  { id: "n-respiration", unit: "Plant physiology", name: "Respiration in plants", qcount: 8,
    summary: "Glycolysis to Krebs to ETS — energy accounting of the cell and RQ values.",
    points: [
      "Glycolysis (cytoplasm): net 2 ATP + 2 NADH per glucose.",
      "Link reaction yields acetyl-CoA + CO2 + NADH in mitochondrial matrix.",
      "Krebs cycle: 2 CO2, 3 NADH, 1 FADH2, 1 GTP per turn.",
      "RQ: carbohydrates 1, fats ~0.7, organic acids >1.",
      "ETC on inner membrane; cyanide blocks cytochrome oxidase.",
      "Glycolysis (cytoplasm): glucose → 2 pyruvate, net 2 ATP + 2 NADH; no oxygen needed.",
      "Pyruvate → acetyl-CoA via PDH complex (mitochondrial matrix) releasing CO2.",
      "Krebs cycle: citrate → oxaloacetate, 2 CO2, 3 NADH, 1 FADH2, 1 GTP per turn.",
      "ETC complexes I–IV pump H+; ATP synthase (Complex V) makes ~3 ATP/NADH, ~2/FADH2.",
      "Fermentation regenerates NAD+: lactic acid (muscle) or ethanol + CO2 (yeast).",
    ],
    terms: ["RQ", "Substrate-level phosphorylation", "Cytochrome", "Amphibolic"] },
  { id: "n-growth", unit: "Plant physiology", name: "Plant growth & development", qcount: 7,
    summary: "Auxins to abscisic acid — the five classic hormone families and their signatures.",
    points: [
      "Auxin: apical dominance, phototropism; synthetic 2,4-D a dicot weedicide.",
      "Gibberellin: bolting, internode elongation, germination enzyme induction.",
      "Cytokinin promotes cell division, delays senescence (Richmond-Lang effect).",
      "Abscisic acid = stress hormone closing stomata under drought.",
      "Ethylene: triple response, fruit ripening; senescence promoter.",
      "Arithmetic growth (L = L0 + rt) vs geometric (W = W0·e^rt); S-curve has lag, log, stationary phases.",
      "Auxins: apical dominance, phototropism, rooting (2,4-D weedkiller at high dose).",
      "Gibberellins: bolting, seed germination (α-amylase), parthenocarpy with auxin.",
      "Cytokinins delay senescence (Richmond–Lang effect); ethylene ripens fruit, causes abscission.",
      "ABA is the stress hormone: stomatal closure, dormancy, abscission — largely inhibitory.",
    ],
    terms: ["Apical dominance", "Bolting", "Senescence", "Triple response"] },

  { id: "n-populations", unit: "Ecology", name: "Organisms & populations", qcount: 7,
    summary: "Abiotic responses, adaptations, population growth models and interactions.",
    points: [
      "Homeostasis: regulate, conform, migrate or suspend (hibernation/aestivation).",
      "Exponential growth dN/dt = rN; logistic adds carrying capacity K.",
      "Age pyramids: growing (base-wide), stable, declining.",
      "Mutualism (+/+), competition (−/−), predation/parasitism (+/−), commensalism (+/0).",
      "Gause's competitive exclusion: two species, same niche cannot coexist.",
      "Population attributes: natality, mortality, immigration, emigration, sex ratio, age pyramids.",
      "Exponential (J-curve, dN/dt = rN) vs logistic (S-curve, dN/dt = rN(1 − N/K)) growth.",
      "Interactions: mutualism (+/+), commensalism (+/0), competition (−/−), predation/parasitism (+/−), amensalism (−/0).",
      "Allen's rule (cold = short limbs), Bergmann's (cold = large body), Gloger's (humid = dark).",
      "r-strategists (many small offspring) vs K-strategists (few, cared-for young).",
    ],
    terms: ["Carrying capacity", "Ecological niche", "Brood parasitism", "Mimicry"] },
  { id: "n-ecosystem", unit: "Ecology", name: "Ecosystem & biodiversity", qcount: 8,
    summary: "Energy flow, pyramids, nutrient cycles and why biodiversity hotspots matter.",
    points: [
      "10% law (Lindeman): ~10% energy transfers to next trophic level.",
      "Pyramids of energy always upright; biomass pyramid can invert (sea).",
      "Decomposers recycle detritus; mineralisation releases nutrients.",
      "Hotspots: high endemic richness + habitat loss; Western Ghats one of them.",
      "In-situ conservation (sanctuaries) beats ex-situ (zoos, seed banks) for ecosystems.",
      "Stratification: producers → herbivores → carnivores; only ~10% energy transfers up (Lindeman).",
      "Ecological pyramids: energy always upright; biomass/numbers can invert (pond, tree).",
      "Decomposition: fragmentation → leaching → catabolism → humification → mineralisation.",
      "Succession: pioneer (lichens) → seral stages → climax; hydrarch (water) vs xerarch (rock).",
      "Carbon, phosphorus (sedimentary, no atmosphere), sulphur and water cycles link living and non-living.",
    ],
    terms: ["Standing crop", "Detritivore", "Endemic", "Red Data Book"] },

  { id: "n-transport", unit: "Plant physiology", name: "Transport in plants", qcount: 8,
    summary: "How water climbs a 100-metre tree and how food moves both ways in phloem.",
    points: [
      "Water column: transpiration pull + cohesion-tension (Dixon); xylem vessels are dead tubes.",
      "Root pressure causes guttation at night through hydathodes.",
      "Stomata open when guard cells pump K⁺ in — turgor bows the outer wall.",
      "Phloem translocation is active, bidirectional, and driven by pressure flow (Münch).",
      "Sucrose is the universal transport sugar; loaded into sieve tubes via companion cells.",
      "Apoplast (cell walls, fast) vs symplast (plasmodesmata, regulated) water routes.",
      "Root pressure + transpiration pull + cohesion-tension lifts columns hundreds of feet.",
      "Guttation (hydathodes, dawn drops) differs from transpiration (stomatal vapour).",
      "Phloem translocation follows pressure-flow (Münch): source loading → sink unloading.",
      "Girdling experiment proves phloem carries food (bark ring removal starves roots).",
    ],
    terms: ["Transpiration pull", "Hydathode", "Pressure flow", "Sieve tube"] },
  { id: "n-mineral", unit: "Plant physiology", name: "Mineral nutrition", qcount: 7,
    summary: "Essential elements, their deficiency signatures, and nitrogen fixation partnerships.",
    points: [
      "Macronutrients: N P K Ca Mg S; micronutrients include Fe Mn Zn Cu B Mo Cl Ni.",
      "Mg sits at the centre of chlorophyll; deficiency shows interveinal chlorosis.",
      "Nitrogen fixed by Rhizobium in legume nodules; nitrogenase is oxygen-sensitive (leghaemoglobin shields it).",
      "Nitrification: NH4⁺ → NO2⁻ (Nitrosomonas) → NO3⁻ (Nitrobacter).",
      "Hydroponics proves an element essential: absent → deficient, cannot be replaced.",
      "Macronutrients (N, P, K, Ca, Mg, S) vs micronutrients (Fe, Mn, Zn, Cu, B, Mo, Cl, Ni).",
      "Nitrogen cycle: fixation (Rhizobium, Azotobacter) → nitrification → assimilation → denitrification.",
      "Deficiency signs: chlorosis (N, Mg, Fe), necrosis (Ca, Mg, K), stunting (N, P, K).",
      "Hydroponics grows plants in nutrient solution; aeroponics mists the roots.",
      "Mycorrhizae trade phosphorus for sugars; root nodules house nitrogen-fixing Rhizobium.",
    ],
    terms: ["Chlorosis", "Necrosis", "Leghaemoglobin", "Nitrification"] },
  { id: "n-tissues", unit: "Animal tissues", name: "Structural organisation in animals", qcount: 6,
    summary: "The four tissue families and where each epithelium lives.",
    points: [
      "Epithelia: simple (squamous/cuboidal/columnar), compound for wear surfaces.",
      "Ciliated epithelium lines trachea & fallopian tube; brush border microvilli in PCT.",
      "Connective proper/ cartilage/bone/blood differ by matrix, not cells.",
      "Cardiac muscle: striated, involuntary, intercalated discs with gap junctions.",
      "Neuroglia support neurons; myelin in CNS from oligodendrocytes.",
      "Epithelia: squamous (diffusion), cuboidal (secretion), columnar (absorption), ciliated (movement).",
      "Connective: areolar packing, adipose fat, tendon (muscle–bone), ligament (bone–bone).",
      "Cartilage (avascular, chondrocytes) vs bone (Haversian canals, osteocytes, mineralised).",
      "Blood: RBCs (no nucleus, Hb), WBCs (immunity), platelets (clotting via fibrin).",
      "Muscle: striated voluntary skeletal, unstriated involuntary visceral, branched cardiac (intercalated discs).",
    ],
    terms: ["Intercalated disc", "Areolar tissue", "Osteocyte", "Goblet cell"] },
  { id: "n-microbes", unit: "Microbes & biotech", name: "Microbes in human welfare", qcount: 7,
    summary: "Fermentation friends, sewage engineers, biofertilisers and biocontrol agents.",
    points: [
      "Yeast (Saccharomyces cerevisiae) ferments to ethanol; Lactobacillus curdles milk.",
      "Penicillin — the first antibiotic — from Penicillium notatum (Fleming).",
      "Biogas: methanogens (Methanobacterium) in anaerobic sludge produce CH4.",
      "Rhizobium biofertilises legumes; Azotobacter free-lives; Blue-green algae fix N in paddy.",
      "Bacillus thuringiensis (Bt) toxin genes protect crops (Bt cotton).",
      "Lactobacillus curdles milk; Saccharomyces brews ethanol and bread CO2.",
      "Antibiotics (penicillin from Penicillium) kill bacteria, useless against viruses.",
      "Biogas (methanogens on dung), sewage treatment (aerobic flocs, anaerobic sludge digesters).",
      "Bt cotton carries Cry genes against bollworms; RNAi silences nematode genes.",
      "Vaccines: live-attenuated, inactivated, subunit, mRNA — all train adaptive immunity.",
    ],
    terms: ["Biogas", "Bt toxin", "Biofertiliser", "Statins"] },
  { id: "n-health", unit: "Human health & disease", name: "Human health & disease", qcount: 9,
    summary: "Pathogens, immunity basics and the major disease table every paper loves.",
    points: [
      "Immunity: innate (barriers, phagocytes) vs acquired (B/T lymphocytes, memory).",
      "Antibodies: Y-shaped immunoglobulins; IgG most abundant, IgE allergy mediator.",
      "Malaria: Plasmodium via female Anopheles; sporozoites infect liver first.",
      "AIDS = HIV (retrovirus) destroying helper T cells; ELISA detects antibodies.",
      "Typhoid Salmonella typhi; pneumonia Strep./Haemophilus; amoebiasis Entamoeba.",
      "Innate barriers (skin, lysozyme, phagocytes) vs adaptive humoral (B/antibodies) + cellular (T-cells).",
      "Antibody classes: IgG (placenta), IgA (milk/tears), IgM (first response), IgE (allergy), IgD (B activation).",
      "Malaria (Plasmodium via Anopheles; haemozoin chills), dengue/chikungunya (Aedes), filariasis (Culex).",
      "Cancer: benign (confined) vs malignant (metastasis); oncogenes + failed suppressors drive it.",
      "Drugs: heroin/cocaine (addictive stimulants/depressants) vs adhesion-tested medicines; adolescence risks peer-driven abuse.",
    ],
    terms: ["Sporozoite", "Retrovirus", "Interferons", "Autoimmunity"] },
];

export const NEET_QUESTIONS = [
  { id: "neet-q-01", topic: "Cell: the unit of life",
    q: "The fluid mosaic model of the plasma membrane was proposed by:",
    opts: ["Robertson", "Singer & Nicolson", "Schleiden & Schwann", "Camillo Golgi"], a: 1,
    why: "Singer and Nicolson (1972) described the membrane as a mosaic of proteins drifting in a fluid lipid bilayer." },
  { id: "neet-q-02", topic: "Cell: the unit of life",
    q: "Which organelle is known as the powerhouse of the cell and carries its own circular DNA?",
    opts: ["Ribosome", "Mitochondrion", "Lysosome", "Golgi apparatus"], a: 1,
    why: "Mitochondria possess their own DNA and 70S ribosomes — semi-autonomous organelles producing most cellular ATP." },
  { id: "neet-q-03", topic: "Cell cycle & division",
    q: "Crossing over between homologous chromosomes occurs during which substage of prophase-I?",
    opts: ["Leptotene", "Zygotene", "Pachytene", "Diplotene"], a: 2,
    why: "Recombination nodules appear at pachytene, where non-sister chromatids of bivalents exchange segments." },
  { id: "neet-q-04", topic: "Biomolecules",
    q: "An enzyme without its cofactor is called a(n):",
    opts: ["Holoenzyme", "Apoenzyme", "Coenzyme", "Zymogen"], a: 1,
    why: "Apoenzyme = inactive protein alone; binding the cofactor completes the catalytic holoenzyme." },
  { id: "neet-q-05", topic: "Digestion & absorption",
    q: "Bile helps fat digestion but contains no enzyme because it:",
    opts: ["hydrolyses triglycerides directly", "only emulsifies fats into micelles", "activates trypsinogen", "absorbs vitamins"], a: 1,
    why: "Bile salts lower surface tension and emulsify large fat globules, raising surface area for pancreatic lipase." },
  { id: "neet-q-06", topic: "Body fluids & circulation",
    q: "The pacemaker of the human heart is the:",
    opts: ["AV node", "SA node", "Bundle of His", "Purkinje fibres"], a: 1,
    why: "The sinoatrial node generates impulses fastest (~70/min) and sets the rhythm for the whole myocardium." },
  { id: "neet-q-07", topic: "Breathing & gas exchange",
    q: "Most carbon dioxide in blood is transported as:",
    opts: ["carbaminohaemoglobin", "dissolved CO2 in plasma", "bicarbonate ions", "carbonic acid"], a: 2,
    why: "About 70% travels as HCO3⁻ formed via carbonic anhydrase in RBCs." },
  { id: "neet-q-08", topic: "Excretory products & elimination",
    q: "The functional unit of the kidney is the:",
    opts: ["Neuron", "Nephron", "Alveolus", "Glomerulus alone"], a: 1,
    why: "Each nephron performs ultrafiltration, reabsorption and secretion — roughly a million per kidney." },
  { id: "neet-q-09", topic: "Excretory products & elimination",
    q: "Healthy GFR is approximately:",
    opts: ["12.5 mL/min", "25 mL/min", "125 mL/min", "1250 mL/min"], a: 2,
    why: "~125 mL/min, i.e., about 180 litres filtered per day — nearly all reabsorbed." },
  { id: "neet-q-10", topic: "Neural control & coordination",
    q: "The resting membrane potential of a typical neuron is closest to:",
    opts: ["+30 mV", "0 mV", "−35 mV", "−70 mV"], a: 3,
    why: "Na⁺/K⁺ pump electrogenesis plus K⁺ leak maintains about −70 mV inside relative to outside." },
  { id: "neet-q-11", topic: "Neural control & coordination",
    q: "Saltatory conduction of nerve impulse occurs in:",
    opts: ["unmyelinated axons", "myelinated axons at nodes of Ranvier", "dendrites only", "synaptic cleft"], a: 1,
    why: "Impulses leap node-to-node over insulated myelin, greatly speeding conduction." },
  { id: "neet-q-12", topic: "Chemical coordination",
    q: "ADH (vasopressin) is synthesised in the hypothalamus but released from the:",
    opts: ["anterior pituitary", "posterior pituitary", "adrenal cortex", "thyroid"], a: 1,
    why: "Hypothalamic neurons send axons to posterior pituitary, which stores and secretes ADH and oxytocin." },
  { id: "neet-q-13", topic: "Principles of inheritance",
    q: "In a Mendelian dihybrid cross, the F2 phenotypic ratio is:",
    opts: ["3:1", "1:2:1", "9:3:3:1", "1:1:1:1"], a: 2,
    why: "Independent assortment of two heterozygous gene pairs produces 9:3:3:1 in F2." },
  { id: "neet-q-14", topic: "Principles of inheritance",
    q: "Down syndrome results from trisomy of chromosome:",
    opts: ["18", "21", "13", "X"], a: 1,
    why: "Non-disjunction producing an extra chromosome 21 (trisomy-21) causes Down syndrome." },
  { id: "neet-q-15", topic: "Molecular basis of inheritance",
    q: "The enzyme that unwinds the DNA double helix during replication is:",
    opts: ["DNA ligase", "DNA polymerase", "Helicase", "Primase"], a: 2,
    why: "Helicase breaks hydrogen bonds and unwinds the parental duplex at the replication fork." },
  { id: "neet-q-16", topic: "Molecular basis of inheritance",
    q: "The inducer of the lac operon in E. coli is:",
    opts: ["lactose itself", "allolactose", "glucose", "tryptophan"], a: 1,
    why: "Allolactose (a lactose isomer) binds the repressor, freeing the operator so transcription begins." },
  { id: "neet-q-17", topic: "Evolution",
    q: "Darwin's Galapagos finches are the classic example of:",
    opts: ["convergent evolution", "adaptive radiation", "genetic drift", "industrial melanism"], a: 1,
    why: "One ancestral seed-eating stock radiated into many beak-forms exploiting different niches — adaptive radiation." },
  { id: "neet-q-18", topic: "Human reproduction",
    q: "Ovulation in the human menstrual cycle is triggered by a surge of:",
    opts: ["FSH", "LH", "progesterone", "prolactin"], a: 1,
    why: "A mid-cycle sharp LH spike (around day 14) ruptures the mature Graafian follicle." },
  { id: "neet-q-19", topic: "Human reproduction",
    q: "The pregnancy-test hormone hCG is secreted by:",
    opts: ["anterior pituitary", "corpus luteum only", "chorionic villi / placenta", "ovarian follicle"], a: 2,
    why: "Trophoblast/chorionic layers produce hCG which sustains the corpus luteum until the placenta takes over." },
  { id: "neet-q-20", topic: "Plant kingdom",
    q: "In bryophytes the dominant photosynthetic phase is the:",
    opts: ["sporophyte", "gametophyte", "prothallus", "sporogenous tissue"], a: 1,
    why: "Bryophyte gametophyte is green and independent; the sporophyte depends partly or wholly on it." },
  { id: "neet-q-21", topic: "Photosynthesis",
    q: "Kranz anatomy with large bundle-sheath cells is characteristic of:",
    opts: ["C3 plants", "C4 plants", "CAM plants only", "aquatic hydrophytes"], a: 1,
    why: "C4 leaves concentrate CO2 in bundle-sheath cells via the Hatch-Slack pathway — Kranz anatomy is the giveaway." },
  { id: "neet-q-22", topic: "Photosynthesis",
    q: "The enzyme responsible for carboxylation in the Calvin cycle is:",
    opts: ["PEP carboxylase", "RuBisCO", "ATP synthase", "Nitrogenase"], a: 1,
    why: "Ribulose bisphosphate carboxylase-oxygenase fixes CO2 onto RuBP — also its oxygenase activity causes photorespiration." },
  { id: "neet-q-23", topic: "Respiration in plants",
    q: "The respiratory quotient (RQ) of fats during aerobic respiration is approximately:",
    opts: ["1.0", "0.7", "greater than 1", "zero"], a: 1,
    why: "Fats need more O2 per CO2 evolved (oxygen-rich carbohydrates don't), giving RQ < 1, near 0.7." },
  { id: "neet-q-24", topic: "Plant growth & development",
    q: "Apical dominance in plants is chiefly caused by:",
    opts: ["gibberellin", "auxin", "cytokinin", "ethylene"], a: 1,
    why: "Auxin from the apex suppresses lateral buds; decapitation relieves dominance, and auxin paste restores it." },
  { id: "neet-q-25", topic: "Ecosystem & biodiversity",
    q: "The 10% law of energy transfer across trophic levels was given by:",
    opts: ["Odum", "Lindeman", "Tansley", "Elton"], a: 1,
    why: "Lindeman (1942) quantified that roughly a tenth of energy passes to the next trophic level." },
  { id: "neet-q-26", topic: "Organisms & populations",
    q: "Two species competing for exactly the same niche cannot coexist permanently — this is:",
    opts: ["character displacement", "Gause's competitive exclusion principle", "Allen's rule", "Bergmann's rule"], a: 1,
    why: "Gause's experiments with Paramecium showed the inferior competitor is excluded when niches fully overlap." },
  { id: "neet-q-27", topic: "Transport in plants",
    q: "Water rises to the top of tall trees primarily because of:",
    opts: ["root pressure", "transpiration pull with cohesion-tension", "capillarity of xylem walls alone", "active pumping by xylem parenchyma"], a: 1,
    why: "Transpiration creates negative pressure; cohesive water columns hold under tension (Dixon's cohesion-tension theory)." },
  { id: "neet-q-28", topic: "Transport in plants",
    q: "Stomata open when guard cells:",
    opts: ["lose K⁺ and become flaccid", "accumulate K⁺ and turn turgid", "become plasmolysed", "secrete abscisic acid"], a: 1,
    why: "K⁺ influx lowers water potential, water enters, turgid guard cells bow outward opening the pore." },
  { id: "neet-q-29", topic: "Mineral nutrition",
    q: "The metal atom at the centre of the chlorophyll molecule is:",
    opts: ["Iron", "Magnesium", "Zinc", "Manganese"], a: 1,
    why: "Mg²⁺ sits in the porphyrin ring of chlorophyll — its deficiency causes interveinal chlorosis." },
  { id: "neet-q-30", topic: "Mineral nutrition",
    q: "The enzyme nitrogenase is protected from oxygen inside legume nodules by:",
    opts: ["haemoglobin of blood", "leghaemoglobin", "cytochrome oxidase", "catalase"], a: 1,
    why: "Leghaemoglobin, an oxygen-scavenging pigment produced cooperatively by plant and Rhizobium, buffers free O2." },
  { id: "neet-q-31", topic: "Structural organisation in animals",
    q: "Ciliated epithelium is characteristically found lining the:",
    opts: ["skin surface", "trachea and fallopian tube", "blood vessels only", "bone marrow"], a: 1,
    why: "Cilia sweep mucus in the respiratory tract and move the ovum along the oviduct." },
  { id: "neet-q-32", topic: "Structural organisation in animals",
    q: "Cardiac muscle differs from skeletal muscle because it is:",
    opts: ["striated and voluntary", "non-striated and involuntary", "striated, involuntary with intercalated discs", "multinucleate and voluntary"], a: 2,
    why: "Cardiac muscle is myogenic and involuntary yet striated; intercalated discs electrically couple fibres." },
  { id: "neet-q-33", topic: "Microbes in human welfare",
    q: "Penicillin, the first discovered antibiotic, is obtained from:",
    opts: ["bacteria", "a fungus (Penicillium)", "a blue-green alga", "a virus"], a: 1,
    why: "Fleming noticed Penicillium notatum lysing staphylococcal colonies — the mould yields penicillin." },
  { id: "neet-q-34", topic: "Microbes in human welfare",
    q: "Methane-rich biogas is produced by anaerobic microbes called:",
    opts: ["nitrosomonas", "methanogens", "lactobacilli", "streptomyces"], a: 1,
    why: "Methanogens like Methanobacterium ferment organic matter into CH4 in biogas plants." },
  { id: "neet-q-35", topic: "Human health & disease",
    q: "The infective stage of Plasmodium injected by the female Anopheles mosquito is the:",
    opts: ["trophozoite", "merozoite", "gametocyte", "sporozoite"], a: 3,
    why: "Sporozoites travel in mosquito saliva to human liver cells, where schizogony begins." },
  { id: "neet-q-36", topic: "Human health & disease",
    q: "The most abundant antibody in human blood, crossing the placenta, is:",
    opts: ["IgA", "IgE", "IgG", "IgM"], a: 2,
    why: "IgG dominates serum immunoglobulin and is the only class transported across the placenta for passive immunity." },
  { id: "neet-q-37", topic: "Cell: the unit of life",
    q: "Which of these organelles is semi-autonomous because it has its own DNA and ribosomes?",
    opts: ["Golgi apparatus", "Lysosome", "Chloroplast", "Peroxisome"], a: 2,
    why: "Chloroplasts (like mitochondria) carry circular DNA and 70S ribosomes — supporting the endosymbiont idea." },
];
