/* TeachMeJEE — previous-year question bank.
   exam: "main" | "adv" · year: paper year · chap/chapName link back to the roadmap. */

export const PYQS = [
  { id: "pyq-p-01", year: 2023, exam: "main", subject: "P", chap: "P-kinematics", chapName: "Kinematics",
    q: "A ball is dropped from a height of 20 m. Taking g = 10 m/s², the time it takes to reach the ground is:",
    opts: ["1 s", "√2 s", "2 s", "4 s"], a: 2,
    why: "h = ½gt² → t = √(2h/g) = √(2·20/10) = √4 = 2 s." },
  { id: "pyq-p-02", year: 2022, exam: "main", subject: "P", chap: "P-current", chapName: "Current electricity",
    q: "A wire carries a constant current I. If its diameter is doubled while the current stays the same, the drift velocity of electrons becomes:",
    opts: ["double", "half", "one-fourth", "unchanged"], a: 2,
    why: "v_d = I/(neA). Doubling diameter quadruples area A, so v_d falls to one-fourth." },
  { id: "pyq-p-03", year: 2021, exam: "main", subject: "P", chap: "P-dual", chapName: "Dual nature of matter",
    q: "The dimensional formula of Planck's constant is:",
    opts: ["[MLT⁻²]", "[ML²T⁻¹]", "[ML²T⁻²]", "[M²L T⁻¹]"], a: 1,
    why: "E = hν → h = E/ν. Energy has dimensions ML²T⁻² and frequency T⁻¹, giving h = [ML²T⁻¹]." },
  { id: "pyq-p-04", year: 2020, exam: "main", subject: "P", chap: "P-rayoptics", chapName: "Ray optics",
    q: "An object is placed 30 cm from a convex lens of focal length 20 cm. The image distance is:",
    opts: ["12 cm", "50 cm", "60 cm", "120 cm"], a: 2,
    why: "1/v − 1/u = 1/f with u = −30, f = +20 → 1/v = 1/20 − 1/30 = 1/60 → v = +60 cm (real, inverted)." },
  { id: "pyq-p-05", year: 2019, exam: "adv", subject: "P", chap: "P-rotation", chapName: "Rotational motion",
    q: "The moment of inertia of a uniform ring of mass M and radius R about a diameter is:",
    opts: ["MR²", "MR²/2", "MR²/4", "2MR²/5"], a: 1,
    why: "About its axis a ring has I = MR²; by symmetry every diameter axis carries half of that: MR²/2." },
  { id: "pyq-p-06", year: 2022, exam: "main", subject: "P", chap: "P-ktg", chapName: "Kinetic theory",
    q: "A Carnot engine works between a source at 500 K and a sink at 300 K. Its efficiency is:",
    opts: ["20%", "40%", "60%", "80%"], a: 1,
    why: "η = 1 − T_c/T_h = 1 − 300/500 = 0.4 = 40%." },
  { id: "pyq-p-07", year: 2023, exam: "main", subject: "P", chap: "P-dual", chapName: "Photoelectric effect",
    q: "In a photoelectric experiment the stopping potential V₀ is plotted against the light frequency ν. The slope of the straight line equals:",
    opts: ["h", "e", "h/e", "e/h"], a: 2,
    why: "eV₀ = hν − φ → V₀ = (h/e)ν − φ/e. The slope is h/e; the magnitude of the intercept gives φ/e." },
  { id: "pyq-p-08", year: 2022, exam: "main", subject: "P", chap: "P-emi", chapName: "EMI & AC",
    q: "An ideal transformer steps the voltage up 10 times. Neglecting losses, the secondary current compared to the primary current is:",
    opts: ["10× larger", "10× smaller", "unchanged", "100× smaller"], a: 1,
    why: "For an ideal transformer power is conserved: V_pI_p = V_sI_s. Raising V by 10 lowers I by 10." },
  { id: "pyq-p-09", year: 2020, exam: "main", subject: "P", chap: "P-fluids", chapName: "Fluid mechanics",
    q: "For small spheres falling under laminar conditions in the same fluid, terminal velocity is proportional to:",
    opts: ["r", "r²", "1/r", "1/r²"], a: 1,
    why: "v_t = 2r²(ρ−σ)g / 9η — Stokes' law balance gives v_t ∝ r²." },
  { id: "pyq-p-10", year: 2024, exam: "main", subject: "P", chap: "P-semi", chapName: "Semiconductors",
    q: "A Zener diode used as a voltage regulator is operated in:",
    opts: ["forward bias below knee", "reverse breakdown", "forward saturation", "unbiased mode"], a: 1,
    why: "In reverse breakdown the Zener voltage stays nearly constant over a wide current range — ideal for regulation." },
  { id: "pyq-p-11", year: 2019, exam: "main", subject: "P", chap: "P-gravitation", chapName: "Gravitation",
    q: "A planet has mass and radius both twice those of Earth. Its escape velocity relative to Earth's (v_e) is:",
    opts: ["v_e/2", "v_e", "√2·v_e", "2·v_e"], a: 1,
    why: "v_e = √(2GM/R). Doubling M raises v_e by √2; doubling R lowers it by √2 — net effect zero." },
  { id: "pyq-p-12", year: 2022, exam: "main", subject: "P", chap: "P-shm", chapName: "Oscillations",
    q: "In SHM, x = A sin ωt. The speed of the particle is maximum when:",
    opts: ["x = ±A", "x = 0", "a is maximum", "t = π/(2ω) only"], a: 1,
    why: "v = Aω cos ωt peaks at ωt = 0, i.e. at the mean position where displacement and restoring force are zero." },
  { id: "pyq-p-13", year: 2023, exam: "main", subject: "P", chap: "P-waves", chapName: "Waves & sound",
    q: "Two tuning forks of frequencies 512 Hz and 508 Hz are sounded together. The beat frequency heard is:",
    opts: ["2 Hz", "4 Hz", "8 Hz", "1020 Hz"], a: 1,
    why: "Beats occur at |f₁ − f₂| = |512 − 508| = 4 Hz." },
  { id: "pyq-p-14", year: 2022, exam: "main", subject: "P", chap: "P-magnet", chapName: "Magnetic effects",
    q: "A charged particle moving parallel to a uniform magnetic field experiences a force that is:",
    opts: ["qvB", "maximum", "zero", "qvB/2"], a: 2,
    why: "F = qv × B; for v parallel to B, sin θ = 0 so the magnetic force vanishes." },
  { id: "pyq-p-15", year: 2024, exam: "main", subject: "P", chap: "P-atoms", chapName: "Atoms & spectra",
    q: "The Balmer transition n = 3 → n = 2 in hydrogen emits a photon of wavelength approximately:",
    opts: ["486 nm (blue-green)", "656 nm (red)", "121 nm (UV)", "1875 nm (IR)"], a: 1,
    why: "1/λ = R(1/4 − 1/9) = 5R/36 → λ ≈ 656 nm, the red H-alpha line of the Balmer series." },

  { id: "pyq-c-01", year: 2023, exam: "main", subject: "C", chap: "C-mole", chapName: "Some basic concepts",
    q: "The number of moles of CO₂ in 11.2 L at STP is:",
    opts: ["0.25", "0.5", "1.0", "2.0"], a: 1,
    why: "At STP 1 mol occupies 22.4 L → n = 11.2/22.4 = 0.5 mol." },
  { id: "pyq-c-02", year: 2022, exam: "main", subject: "C", chap: "C-bonding", chapName: "Chemical bonding",
    q: "The hybridisation of sulphur in SF₆ is:",
    opts: ["sp³", "sp³d", "sp³d²", "sp²d"], a: 2,
    why: "Six σ-bond pairs around S give an octahedral geometry requiring sp³d² hybrids." },
  { id: "pyq-c-03", year: 2019, exam: "adv", subject: "C", chap: "C-bonding", chapName: "Molecular orbital theory",
    q: "According to MO theory the bond order of the superoxide ion O₂⁻ is:",
    opts: ["1", "1.5", "2", "2.5"], a: 1,
    why: "O₂ has bond order 2; adding one electron to π* lowers it by ½ → O₂⁻ has bond order 1.5." },
  { id: "pyq-c-04", year: 2021, exam: "main", subject: "C", chap: "C-orgbasic", chapName: "Organic basics",
    q: "The IUPAC name of CH₃–CH(Br)–CH₃ is:",
    opts: ["1-bromopropane", "2-bromopropane", "propyl bromide", "1,2-dibromopropane"], a: 1,
    why: "Number from the end nearer Br: three-carbon chain with bromo on C-2 → 2-bromopropane." },
  { id: "pyq-c-05", year: 2020, exam: "main", subject: "C", chap: "C-bonding", chapName: "Halogen acids",
    q: "Among HF, HCl, HBr and HI, the strongest acid in water is:",
    opts: ["HF", "HCl", "HBr", "HI"], a: 3,
    why: "Bond strength falls H–F > H–Cl > H–Br > H–I; the weakest bond ionises most readily, so HI is strongest." },
  { id: "pyq-c-06", year: 2022, exam: "main", subject: "C", chap: "C-redox", chapName: "Electrochemistry",
    q: "For a spontaneous cell reaction at standard conditions, ΔG° relates to E°_cell as:",
    opts: ["ΔG° = nFE°cell > 0", "ΔG° = −nFE°cell < 0", "ΔG° = −nFE°cell > 0", "ΔG° is independent of E°cell"], a: 1,
    why: "ΔG° = −nFE°cell; a positive cell potential therefore makes ΔG° negative — the sign of spontaneity." },
  { id: "pyq-c-07", year: 2024, exam: "main", subject: "C", chap: "C-kinetics", chapName: "Chemical kinetics",
    q: "The half-life of a first-order reaction is independent of:",
    opts: ["temperature", "the rate constant", "initial reactant concentration", "activation energy"], a: 2,
    why: "t½ = ln2/k for first order — no concentration term appears, unlike zero or second order." },
  { id: "pyq-c-08", year: 2021, exam: "main", subject: "C", chap: "C-atomic", chapName: "Coordination compounds",
    q: "The complex [Co(NH₃)₆]³⁺ is diamagnetic because:",
    opts: ["Co³⁺ is d⁴ high-spin", "NH₃ is a weak field ligand", "it is d⁶ low-spin with all electrons paired", "cobalt has no unpaired d electrons ever"], a: 2,
    why: "Co³⁺ is d⁶; strong-field NH₃ pairs all six t₂g electrons (t₂g⁶ e_g⁰) — no unpaired electrons remain." },
  { id: "pyq-c-09", year: 2019, exam: "main", subject: "C", chap: "C-atomic", chapName: "Periodic trends",
    q: "The correct decreasing order of ionic radii among the isoelectronic species N³⁻, O²⁻, F⁻, Na⁺ is:",
    opts: ["Na⁺ > F⁻ > O²⁻ > N³⁻", "N³⁻ > O²⁻ > F⁻ > Na⁺", "F⁻ > Na⁺ > N³⁻ > O²⁻", "O²⁻ > N³⁻ > Na⁺ > F⁻"], a: 1,
    why: "All ten electrons; greater negative charge means less nuclear pull per electron, so size grows as Na⁺ < F⁻ < O²⁻ < N³⁻." },
  { id: "pyq-c-10", year: 2023, exam: "main", subject: "C", chap: "C-orgbasic", chapName: "Addition reactions",
    q: "Addition of HBr to propene gives mainly 2-bromopropane. This follows:",
    opts: ["anti-Markovnikov rule", "Markovnikov's rule", "Hund's rule", "Hess's law"], a: 1,
    why: "H adds to the carbon with more hydrogens, forming the more stable secondary carbocation — Markovnikov addition." },
  { id: "pyq-c-11", year: 2020, exam: "main", subject: "C", chap: "C-equil", chapName: "Ionic equilibrium",
    q: "The pH of a 0.001 M NaOH solution at 25 °C is:",
    opts: ["3", "7", "11", "13"], a: 2,
    why: "[OH⁻] = 10⁻³ → pOH = 3, so pH = 14 − 3 = 11." },
  { id: "pyq-c-12", year: 2021, exam: "main", subject: "C", chap: "C-thermo", chapName: "Thermodynamics",
    q: "For the isothermal reversible expansion of an ideal gas, ΔU equals:",
    opts: ["−nRT ln(V₂/V₁)", "0", "q", "w"], a: 1,
    why: "Internal energy of an ideal gas depends only on temperature; isothermal means ΔT = 0, hence ΔU = 0." },
  { id: "pyq-c-13", year: 2022, exam: "main", subject: "C", chap: "C-gas", chapName: "Gas laws",
    q: "At constant temperature, if the volume of a fixed amount of ideal gas is halved, its pressure:",
    opts: ["halves", "doubles", "stays equal", "quadruples"], a: 1,
    why: "Boyle's law PV = constant at fixed T; halving V forces P to double." },
  { id: "pyq-c-14", year: 2023, exam: "main", subject: "C", chap: "C-equil", chapName: "Solubility equilibria",
    q: "Adding a common ion to a saturated solution of a sparingly soluble salt will:",
    opts: ["raise its solubility", "lower its solubility", "not change solubility", "increase K_sp"], a: 1,
    why: "K_sp is fixed at a given temperature; extra common ion pushes the equilibrium back — solubility drops (common-ion effect)." },
  { id: "pyq-c-15", year: 2020, exam: "adv", subject: "C", chap: "C-carbonyl", chapName: "Aldehydes & ketones",
    q: "A carbonyl compound undergoes aldol condensation only if it possesses:",
    opts: ["an aromatic ring", "at least one α-hydrogen", "a β-hydrogen", "a leaving group on carbonyl carbon"], a: 1,
    why: "The enolate formed by removing an α-H attacks another carbonyl; without α-hydrogens (e.g. benzaldehyde alone, formaldehyde) no aldol occurs." },

  { id: "pyq-m-01", year: 2023, exam: "main", subject: "M", chap: "M-complex", chapName: "Complex numbers",
    q: "The value of i²⁰²³ is:",
    opts: ["1", "i", "−i", "−1"], a: 2,
    why: "2023 = 4·505 + 3, so i²⁰²³ = i³ = i²·i = −i." },
  { id: "pyq-m-02", year: 2022, exam: "main", subject: "M", chap: "M-diff", chapName: "Differentiation",
    q: "d/dx (xˣ) equals:",
    opts: ["x·xˣ⁻¹", "xˣ ln x", "xˣ(1 + ln x)", "xˣ/x"], a: 2,
    why: "Write y = xˣ → ln y = x ln x → y'/y = 1 + ln x → y' = xˣ(1 + ln x)." },
  { id: "pyq-m-03", year: 2021, exam: "main", subject: "M", chap: "M-integ", chapName: "Integration",
    q: "∫ dx/(1 + x²) equals:",
    opts: ["ln(1+x²) + C", "tan⁻¹x + C", "sin⁻¹x + C", "½ln|x²+1| + C"], a: 1,
    why: "Standard result: the antiderivative of 1/(1+x²) is arctan x." },
  { id: "pyq-m-04", year: 2020, exam: "main", subject: "M", chap: "M-vectors", chapName: "Vectors",
    q: "If a · b = 0 with neither vector zero, then a and b are:",
    opts: ["parallel", "perpendicular", "equal", "anti-parallel"], a: 1,
    why: "a·b = |a||b|cos θ = 0 forces cos θ = 0 → θ = 90°." },
  { id: "pyq-m-05", year: 2019, exam: "main", subject: "M", chap: "M-seq", chapName: "Sequences & series",
    q: "The 10th term of the arithmetic progression 2, 5, 8, … is:",
    opts: ["26", "27", "29", "32"], a: 2,
    why: "aₙ = a + (n−1)d = 2 + 9·3 = 29." },
  { id: "pyq-m-06", year: 2022, exam: "main", subject: "M", chap: "M-prob", chapName: "Probability",
    q: "Two fair dice are rolled. The probability that the sum is 7 is:",
    opts: ["1/6", "1/8", "5/36", "7/36"], a: 0,
    why: "6 favourable ordered pairs out of 36 → 6/36 = 1/6." },
  { id: "pyq-m-07", year: 2021, exam: "main", subject: "M", chap: "M-conics", chapName: "Conic sections",
    q: "The eccentricity of the ellipse x²/25 + y²/16 = 1 is:",
    opts: ["4/5", "3/5", "√5/5", "1/5"], a: 1,
    why: "a = 5, b = 4 → e = √(1 − b²/a²) = √(1 − 16/25) = 3/5." },
  { id: "pyq-m-08", year: 2020, exam: "main", subject: "M", chap: "M-limits", chapName: "Limits",
    q: "lim(x→0) sin 3x / x equals:",
    opts: ["1", "1/3", "3", "does not exist"], a: 2,
    why: "sin 3x/x = 3 · sin 3x/(3x) → 3 · 1 = 3 using the standard limit." },
  { id: "pyq-m-09", year: 2023, exam: "main", subject: "M", chap: "M-complex", chapName: "Modulus",
    q: "The modulus of the complex number 3 + 4i is:",
    opts: ["5", "7", "12", "25"], a: 0,
    why: "|z| = √(3² + 4²) = √25 = 5." },
  { id: "pyq-m-10", year: 2022, exam: "main", subject: "M", chap: "M-trig", chapName: "Trigonometry",
    q: "sin 120° equals:",
    opts: ["1/2", "√3/2", "−√3/2", "√2/2"], a: 1,
    why: "120° is in quadrant II where sine is positive: sin 120° = sin 60° = √3/2." },
  { id: "pyq-m-11", year: 2021, exam: "main", subject: "M", chap: "f-arithmetic", chapName: "Basic maths",
    q: "The sum of the first 20 natural numbers is:",
    opts: ["190", "200", "210", "220"], a: 2,
    why: "n(n+1)/2 = 20·21/2 = 210." },
  { id: "pyq-m-12", year: 2024, exam: "main", subject: "M", chap: "f-algebra", chapName: "Binomial theorem",
    q: "The coefficient of x² in the expansion of (1 + x)⁵ is:",
    opts: ["5", "10", "15", "20"], a: 1,
    why: "C(5,2) = 10." },
  { id: "pyq-m-13", year: 2019, exam: "adv", subject: "M", chap: "M-diff", chapName: "Curve sketching",
    q: "The curve y = x³ − 3x has a point of inflection at:",
    opts: ["x = −1", "x = 0", "x = 1", "no inflection point"], a: 1,
    why: "y'' = 6x changes sign at x = 0 (concave down left, concave up right) — inflection there; extrema at ±1 are not inflections." },
  { id: "pyq-m-14", year: 2020, exam: "main", subject: "M", chap: "M-vectors", chapName: "3D geometry",
    q: "The distance of the point (1, 2, 3) from the plane z = 0 is:",
    opts: ["1", "2", "3", "√14"], a: 2,
    why: "z = 0 is the xy-plane; distance is simply |z-coordinate| = 3." },
];
