/* JEE Planner — practice question bank. Each question maps to a concept id from data.js. */

export const QUESTIONS = [
  { c: "P-kinematics", q: "A ball is dropped from rest. In the first 2 s it falls (g = 10 m/s²):", opts: ["10 m", "20 m", "40 m", "5 m"], a: 1, why: "s = ½gt² = ½·10·4 = 20 m." },
  { c: "P-kinematics", q: "A car accelerates uniformly from rest to 20 m/s in 4 s. Its acceleration is:", opts: ["5 m/s²", "80 m/s²", "4 m/s²", "0.2 m/s²"], a: 0, why: "a = Δv/Δt = 20/4 = 5 m/s²." },
  { c: "P-laws", q: "Newton's first law states that a body continues in uniform motion unless acted on by a net:", opts: ["force", "velocity", "mass", "impulse"], a: 0, why: "A net external force changes the state of motion (law of inertia)." },
  { c: "P-laws", q: "For every action there is an equal and opposite reaction — this is Newton's:", opts: ["first law", "second law", "third law", "zeroth law"], a: 2, why: "Newton's third law pairs every action with an equal and opposite reaction." },
  { c: "P-wpe", q: "Work done by a conservative force along a closed path is:", opts: ["zero", "maximum", "negative", "infinite"], a: 0, why: "Work depends only on endpoints; a closed loop returns to the start, so net work is zero." },
  { c: "P-shm", q: "In SHM, the time period of a mass m on a spring of constant k is:", opts: ["2π√(m/k)", "2π√(k/m)", "π√(m/k)", "2π(m/k)"], a: 0, why: "T = 2π√(m/k) — independent of amplitude." },
  { c: "P-gravitation", q: "The value of g at a height h above the Earth (h much smaller than R) is approximately:", opts: ["g(1 − 2h/R)", "g(1 + 2h/R)", "g(1 − h/R)", "g"], a: 0, why: "g' ≈ g(1 − 2h/R) for small heights above the surface." },
  { c: "P-waves", q: "Sound waves in air are:", opts: ["transverse", "longitudinal", "electromagnetic", "both transverse and longitudinal"], a: 1, why: "Sound propagates as compressions and rarefactions — a longitudinal wave." },
  { c: "P-current", q: "Ohm's law states V = IR. If I doubles while R is fixed, V:", opts: ["halves", "doubles", "stays same", "quadruples"], a: 1, why: "V is directly proportional to I for constant resistance." },
  { c: "P-current", q: "Resistors R and 2R in series have equivalent resistance:", opts: ["2R/3", "R/2", "3R", "R"], a: 2, why: "Series resistances add: R + 2R = 3R." },
  { c: "P-rayoptics", q: "A convex lens forms a real image when the object is placed beyond its:", opts: ["principal focus", "centre of curvature", "optical centre", "focal length"], a: 0, why: "For u > f, a convex lens forms a real, inverted image." },
  { c: "P-rayoptics", q: "The focal length of a plane mirror is:", opts: ["zero", "infinite", "negative", "half its radius"], a: 1, why: "A plane mirror is a sphere of infinite radius, so f = ∞." },
  { c: "P-emi", q: "Faraday's law relates the induced emf to the rate of change of:", opts: ["current", "voltage", "magnetic flux", "resistance"], a: 2, why: "ε = −dΦ/dt — induced emf equals the rate of change of magnetic flux." },
  { c: "P-dual", q: "The photoelectric effect is best explained by treating light as:", opts: ["a continuous wave", "a stream of photons", "a sound wave", "a static field"], a: 1, why: "Photons of energy hf eject electrons; below the threshold frequency no electrons are emitted." },
  { c: "P-atoms", q: "In the Bohr model, the energy of the electron in the nth orbit varies as:", opts: ["1/n²", "n²", "1/n", "n"], a: 0, why: "Eₙ = −13.6/n² eV for hydrogen." },
  { c: "P-semi", q: "A p-n junction diode conducts when it is:", opts: ["reverse biased", "forward biased", "unbiased", "always"], a: 1, why: "Forward bias lowers the barrier and allows current flow." },
  { c: "C-mole", q: "How many moles are in 44 g of CO₂? (molar mass 44 g/mol)", opts: ["0.5", "1", "2", "4"], a: 1, why: "n = m/M = 44/44 = 1 mol." },
  { c: "C-mole", q: "Avogadro's number is approximately:", opts: ["6.02 × 10²³", "3.14 × 10²³", "6.02 × 10²²", "9.11 × 10²³"], a: 0, why: "Nₐ ≈ 6.022 × 10²³ particles per mole." },
  { c: "C-gas", q: "At constant temperature, the pressure of an ideal gas varies inversely with its volume — this is:", opts: ["Charles's law", "Boyle's law", "Avogadro's law", "Graham's law"], a: 1, why: "PV = constant at fixed T (Boyle's law)." },
  { c: "C-thermo", q: "In an adiabatic process, which quantity remains constant?", opts: ["temperature", "pressure", "heat exchanged", "Q = 0"], a: 3, why: "Adiabatic means no heat exchange with the surroundings (Q = 0)." },
  { c: "C-atomic", q: "The number of electrons that can occupy the n = 2 shell is:", opts: ["2", "6", "8", "18"], a: 2, why: "Maximum electrons = 2n² = 2(4) = 8." },
  { c: "C-bonding", q: "A bond formed by the sharing of electron pairs between atoms is called:", opts: ["ionic", "covalent", "metallic", "hydrogen"], a: 1, why: "Covalent bonds arise from shared electron pairs." },
  { c: "C-redox", q: "In a redox reaction, oxidation is the:", opts: ["gain of electrons", "loss of electrons", "gain of protons", "loss of protons"], a: 1, why: "Oxidation = loss of electrons; reduction = gain of electrons." },
  { c: "C-electro", q: "The electrode at which oxidation occurs in an electrochemical cell is the:", opts: ["cathode", "anode", "salt bridge", "both"], a: 1, why: "Oxidation happens at the anode; reduction at the cathode." },
  { c: "f-arithmetic", q: "The sum of the first n natural numbers is:", opts: ["n(n+1)/2", "n(n−1)/2", "n²", "n/2"], a: 0, why: "1 + 2 + … + n = n(n+1)/2." },
  { c: "f-algebra", q: "If f(x) = x² and g(x) = x + 1, then f(g(2)) =", opts: ["5", "9", "6", "8"], a: 1, why: "g(2) = 3, f(3) = 9." },
  { c: "M-trig", q: "sin²θ + cos²θ equals:", opts: ["0", "1", "sin 2θ", "2"], a: 1, why: "Pythagorean identity: sin²θ + cos²θ = 1." },
  { c: "M-complex", q: "i² equals:", opts: ["1", "−1", "i", "0"], a: 1, why: "i² = −1 by definition." },
  { c: "M-diff", q: "The derivative of x³ is:", opts: ["3x²", "x²/3", "3x", "x³/3"], a: 0, why: "d/dx (xⁿ) = n·xⁿ⁻¹ = 3x²." },
  { c: "M-diff", q: "If y = eˣ, then dy/dx equals:", opts: ["x·eˣ⁻¹", "eˣ", "eˣ/2", "ln x"], a: 1, why: "d/dx (eˣ) = eˣ." },
  { c: "M-integ", q: "∫₀¹ 2x dx equals:", opts: ["1", "2", "0.5", "4"], a: 0, why: "∫2x dx = x², evaluated 0→1 gives 1." },
  { c: "M-integ", q: "∫ (1/x) dx equals:", opts: ["ln|x| + C", "x²/2 + C", "−1/x² + C", "1/x + C"], a: 0, why: "The antiderivative of 1/x is ln|x| + C." },
  { c: "M-prob", q: "If a fair coin is tossed twice, the probability of two heads is:", opts: ["1/2", "1/4", "1/8", "1"], a: 1, why: "P(HH) = (1/2)(1/2) = 1/4." },
  { c: "M-prob", q: "If P(A) = 0.4 and events A and B are mutually exclusive with P(B) = 0.3, then P(A or B) =", opts: ["0.12", "0.7", "0.1", "0.75"], a: 1, why: "Mutually exclusive: P(A∪B) = P(A) + P(B) = 0.7." },
  { c: "M-vectors", q: "The dot product of two perpendicular vectors is:", opts: ["1", "0", "−1", "their product"], a: 1, why: "a·b = |a||b|cos90° = 0." },
  { c: "M-quad", q: "The roots of x² − 5x + 6 = 0 are:", opts: ["2 and 3", "−2 and −3", "1 and 6", "5 and 6"], a: 0, why: "(x − 2)(x − 3) = 0 gives x = 2, 3." },
  { c: "M-limits", q: "limₓ→₀ (sin x)/x equals:", opts: ["0", "1", "∞", "does not exist"], a: 1, why: "Standard limit: limₓ→₀ sin x / x = 1." },
  { c: "M-seq", q: "In an arithmetic progression, the common difference is constant between:", opts: ["consecutive terms", "squares of terms", "ratios of terms", "logarithms of terms"], a: 0, why: "AP is defined by a constant difference between consecutive terms." },
  { c: "M-conics", q: "The eccentricity of a circle is:", opts: ["0", "1", "2", "√2"], a: 0, why: "A circle is the limiting ellipse with e = 0." },
  { c: "P-rotation", q: "Moment of inertia depends on:", opts: ["mass distribution only", "the axis of rotation", "neither", "both mass distribution and axis"], a: 3, why: "I = Σmr² depends on both the mass distribution and the chosen axis." },
  { c: "P-fluids", q: "Pascal's law states that pressure applied to an enclosed fluid is transmitted:", opts: ["unequally", "equally in all directions", "only downward", "only upward"], a: 1, why: "Pressure is transmitted undiminished and equally throughout an enclosed fluid." },
  { c: "P-ktg", q: "The average kinetic energy of gas molecules is proportional to:", opts: ["absolute temperature", "pressure only", "volume only", "molar mass"], a: 0, why: "KE_avg = (3/2)kT — proportional to absolute temperature." },
  { c: "C-kinetics", q: "The rate of a reaction generally increases with:", opts: ["lower temperature", "higher temperature", "lower concentration", "smaller surface area"], a: 1, why: "Raising temperature increases the fraction of molecules with energy ≥ Eₐ." },
  { c: "C-equil", q: "Le Chatelier's principle states a system at equilibrium will:", opts: ["always shift right", "oppose any change imposed on it", "never change", "become acidic"], a: 1, why: "Equilibrium shifts to counteract an imposed change (concentration, pressure, temperature)." },
  { c: "C-orgbasic", q: "The functional group in an alcohol is:", opts: ["−OH", "−COOH", "−NH₂", "−CHO"], a: 0, why: "Alcohols contain the hydroxyl group −OH." },
  { c: "C-carbonyl", q: "Aldehydes contain which functional group?", opts: ["−CHO", "−COOH", "−OH", "−CO−"], a: 0, why: "The aldehyde group is −CHO (a carbonyl with a hydrogen)." },
  { c: "M-stats", q: "The mean of the numbers 2, 4, 6, 8, 10 is:", opts: ["5", "6", "7", "8"], a: 1, why: "Sum = 30, n = 5, mean = 6." },
  { c: "P-rayoptics", q: "The power of a lens of focal length 0.5 m is:", opts: ["2 D", "0.5 D", "5 D", "0.2 D"], a: 0, why: "P = 1/f (in metres) = 1/0.5 = 2 dioptres." },
  { c: "P-magnet", q: "The magnetic field at the centre of a current loop is proportional to:", opts: ["current", "current squared", "resistance", "radius squared"], a: 0, why: "B ∝ I/R at the centre — directly proportional to current." },
];
